### PR TITLE
Support Rails 5.1.5 and Rails 5.2

### PR DESCRIPTION
**Pull request by jeremyyap**
Method signature of `JoinDependency#instantiate` was changed in [this commit](https://github.com/rails/rails/commit/237f00c8053a017c19103a59732dd9751c138976#diff-06059df8d3dee3101718fb2c01151ad0)

### CODE REVIEW

**Comment by schneidmaster** [comment]
@jeremyyap Thanks for the PR! From the CI, it looks like this change breaks compatibility with Rails 5.0. Can you split your update out into a new patch file, and then add logic [here](https://github.com/aha-app/calculated_attributes/blob/master/lib/calculated_attributes.rb) to select the correct patch based on whether the user has 5.1.5/5.2 or 5.0/5.1 pre 5. It would also be good to add an Appraisal for 5.2.

**Comment by schneidmaster** [comment]
Thanks! For rubocop can you actually just add a line [after here](https://github.com/aha-app/calculated_attributes/blob/master/.rubocop.yml#L7) in the config, I have all the patch files ignored 🙂

**Comment by jeremyyap** [comment]
Done!

**Comment by schneidmaster** [comment]
Thanks! Published as 0.3.0.

**Pull request merged**
